config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  root "events#index"

  resources :events, only: [:index, :show, :create, :new, :edit, :update, :destroy]
  resources :invitations, only: [:index, :show, :create, :new, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :invitations
  has_many :attendees, through: :invitations, source: :user

  validates :title, presence: true, length: { in: 1..100 }
  validates :description, presence: true, length: { in: 1..10000 }

  scope :past, -> { where("date < ?", Time.current) }
  scope :upcoming, -> { where("date >= ?", Time.current) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  has_many :invitations
  has_many :attended_events, through: :invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
# app/controllers/events_controller.rb

class EventsController < ApplicationController
  def index
    @events = Event.all
    @past_events = Event.past
    @upcoming_events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path
  end

  private
    def event_params
      params.require(:event).permit(:title, :description, :date, :exclusive)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
    @invitations = Invitation.all
  end

  def show
    @invitation = Invitation.find(params[:id])
  end

  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invitation_params)
    
    if @invitation.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    redirect_to root_path
  end

  def update
    @invitation = Invitation.find(params[:id])
    
    if @invitation.update(invitation_params)
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def edit
    @invitation = Invitation.find(params[:id])
  end

  private

    def invitation_params
      params.require(:invitation).permit(:event_id, :user_id, :acceptance)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attendance_list.html.erb
<h4>Attending</h4>
<% @event.attendees.each do |attendee| %>
  <% invite = attendee.invitations.find_by(event_id: @event.id) %>
  <ul class="guest-list">
    <li><%= attendee.email if invite.acceptance == true %></li>
  </ul>
<% end %>

app/views/events/_exclusive_invitation_response.html.erb
<% invite = current_user.invitations.find_by(event_id: @event.id) %>
<% if invite.nil? %>
  <%= "This is an exclusive event. You must be privately invited to attend." %>
<% elsif invite.acceptance == true %>
  <%= render 'remove_invitation_form' %>
<% elsif current_user.attended_events.include? @event %>
  <%= render 'exclusive_invitation_form' %>
<% else %>
    Something went wrong. Check back later.
<% end %>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <%= form.label :title, "Name your event" %><br>
  <%= form.text_field :title %><br>
  <br>
  <%= form.label :description, "Describe it a little (or a lot)" %><br>
  <%= form.text_area :description %><br>
  <br>
  <%= form.label :description, "Date and time" %><br>
  <%= form.date_field :date %><br>
  <br>
  <%= form.label :exclusive, "Make this event exclusive? (private invitations only)" %></br>
  <%= form.check_box :exclusive %><br>
  <%= form.submit "Create" %>
<% end %>

app/views/events/_guest_list_form.html.erb
<%= form_with model: Invitation.new do |form| %>
  <% users_with_no_invitation = User.where.not(id: @event.invitations.map { |invitation| invitation.user.id } ) %>
  <% if users_with_no_invitation.present? %>
    <%= form.hidden_field :event_id, :value => @event.id %>
    <div><%= form.collection_select :user_id, users_with_no_invitation.order(:email), :id, :email %> </div>
    <br>
    <div class="flex"><%= form.submit "Send Invitation", class: "invitation-button" %></div>
  <% end %>
<% end %>

app/views/events/_invitation_process.html.erb
<div class="invitation-container">
  <% if @event.exclusive == true %>
    <%= render 'exclusive_invitation_process' %>
    <%= render 'guest_list_process' %>
  <% else %>
    <%= render 'public_invitation_process' %>
  <% end %>
</div>

app/views/events/_past_events.html.erb
<h3 id="past">Past Events</h3>
  <% sorted_past_events = @past_events.sort_by { |event| event['date'] }.reverse %>
  <% sorted_past_events.each do |event| %>
  <div class="past-event-container">
    <ul class="event-list">
      <li class="event-title"><%= event.title %></li>
        <li class="event-date"><%= event.date.strftime("%B %-d %Y") %></li>
        <li>Hosted by: <%= event.creator.email %></li>
        <br>
        <button class="view-link"><%= link_to "Details", event_path(event.id) %>
    </ul>
    </div>
  <% end %>
  

app/views/events/_public_invitation_form.html.erb
<%= form_with model: Invitation.new do |form| %>
  <%= form.hidden_field :event_id, :value => @event.id %>
  <%= form.hidden_field :user_id, :value => current_user.id %>
  <%= form.hidden_field :acceptance, :value => true %>
  <%= form.submit "Accept Invitation", class: "invitation-button" %>
<% end %>

app/views/events/_public_invitation_process.html.erb
<% if user_signed_in? %>
  <%= render 'public_invitation_response' %>
<% else %>
  <p><em>Log in to attend this public event.</em></p>
<% end %>  

app/views/events/_public_invitation_response.html.erb
<% if current_user.attended_events.include? @event %>
  <%= render 'remove_invitation_form' %>
<% else %>
  <%= render 'public_invitation_form' %>
<% end %>

app/views/events/_remove_invitation_form.html.erb
<% if current_user.attended_events.include? @event %>
  You have already accepted this invitation
  <%= button_to 'Remove yourself from this event', invitation_path(current_user.invitations.find_by!(event_id: @event.id)), 
                 method: :delete, data: { confirm: 'Do you really want to remove yourself from this event?' }, class: "invitation-button" %>
<% else %>
  <p>You are not currently attending this event</p>
<% end %>

app/views/events/edit.html.erb
<h2>Edit This Event</h2>

<% if @event.creator == current_user %>
  <%= render 'new_event_form' %>
<% else %>
  <p>Only the Event Creator can edit this event</p>
<% end %>

app/views/events/index.html.erb
<h2>All Events</h2>
<div class="event-index">
  <div>
    <%= render 'upcoming_events' %>
  </div>
  <div>
    <%= render 'past_events' %>
  </div>
</div>

app/views/events/new.html.erb
<h2>Make a New Event</h2>
<%= render 'new_event_form' %>

app/views/events/show.html.erb
<h3 id="show-title"><%= @event.title %></h2>
<div class="show-container">
  <h4 id="show-date"><%= @event.date.strftime("%A, %B %-d, %Y") %></h3>
  <h4>Created by <%= link_to @event.creator.email, user_path(@event.creator) %></h3>
  <p><%= simple_format(@event.description) %></p>
  <div>
    <% past_events = Event.past %>
    <% if past_events.include?(@event) %>
      <p class="event-alert"> This event has passed, but ask how it went!</p>
    <% else %>
      <%= render 'invitation_process' %>
    <% end %>
  </div>
  <div>
    <%= render 'attendance_list' %>
  </div>
  <div>
    <%= render 'creator_edit_links' if @event.creator == current_user %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
 <% if user_signed_in? %>
   <p class="footer-text"><%= link_to current_user.email, edit_user_registration_path%></p>
   <p class="footer-text"><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
 <% else %>
   <p class="footer-text"><%= link_to 'Sign In', new_user_session_path %></p>
   <p class="footer-text"><%= link_to 'Sign Up', new_user_registration_path %></p>
 <% end %>
 <p class="footer-text"><%= link_to 'GitHub', "https://github.com/dm-murphy/private-events#readme"%></p>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar">   
    <h1 class="logo"><%= link_to "Private Events", root_path %></h1>
    <ul class="nav-links">
      <li><%= link_to "All Events", root_path %></li>
      <li><%= link_to "New Event", new_event_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Your Events", user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Log In", new_user_session_path %></li>
      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Settings", edit_user_registration_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <%= render "layouts/navbar" %>
  
  <div class="main-content">

  <% if flash[:notice] %>
    <div>
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div>
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  <%= yield %>

  </div>
  <%= render "layouts/footer" %>
  
  </body>
</html>

app/views/users/_hosted_events.html.erb
<h3 class="user-header">Hosted Events</h3>
<% hosted_events = @user.events %>
<% sorted_hosted_events = hosted_events.sort_by { |event| event['date'] }.reverse %>
<% sorted_hosted_events.each do |event| %>
  <div class="user-event-container">
    <ul class="user-event-list">
      <li class="user-event-title"><%= event.title %></li>
      <li class="user-event-date"><%= event.date.strftime("%B %-d %Y") %></li>
      <br>
      <button class="user-details-button"><%= link_to "Details", event_path(event.id) %>
    </ul>
  </div>
<% end %>

app/views/users/_past_events.html.erb
<h3 class="user-header">Past Events</h3>
<% past_events = @user.attended_events.where("date < ?", Time.current) %>
<% sorted_past_events = past_events.sort_by { |event| event['date'] }.reverse %>
<% sorted_past_events.each do |event| %>
  <div class="user-past-container">
    <ul class="user-event-list">
      <li class="user-event-title"><%= event.title %></li>
      <li class="user-event-date"><%= event.date.strftime("%B %-d %Y") %></li>
      <br>
      <button class="user-details-button"><%= link_to "Details", event_path(event.id) %>
    </ul>
  </div>
<% end %>

app/views/users/_upcoming_events.html.erb
<h3 class="user-header">Upcoming Events</h3>
<% upcoming_events = @user.attended_events.where("date >= ?", Time.current) %>
<% sorted_upcoming_events = upcoming_events.sort_by { |event| event['date'] } %>
<% sorted_upcoming_events.each do |event| %>
  <div class="user-upcoming-container">
    <ul class="user-event-list">
      <li class="user-event-title"><%= event.title %></li>
      <li class="user-event-date"><%= event.date.strftime("%B %-d %Y") %></li>
      <br>
      <button class="user-details-button"><%= link_to "Details", event_path(event.id) %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h2>User Profiles</h2>
<% @users.each do |user| %>
  <li><%= link_to user.email, user_path(user) %></li>
<% end %>

app/views/users/show.html.erb
<h2>User Profile</h2>
<h3><%= @user.email %></h3>
<div class="user-container">
  <div>
    <%= render 'hosted_events' %>
  </div>
  <div>
    <%= render 'upcoming_events' %>
  </div>
  <div>
    <%= render 'past_events' %>
  </div>
</div>